import argparse
import builtins
import json
import os
import runpy
import tempfile
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CUBE_SOURCE = ROOT / "tools" / "numstep" / "NumstepCube.py"


def generate_from_original(puzzle_date, size):
    """Run the original NumstepCube.py unchanged and capture its outputs."""
    if puzzle_date != date.today():
        raise SystemExit(
            "The original NumstepCube.py uses date.today() for its PDF filename; "
            "daily generation therefore only supports today's date."
        )

    import random
    random.seed(f"numstep-cube:{puzzle_date.isoformat()}:{size}")

    original_input = builtins.input
    original_cwd = Path.cwd()

    try:
        with tempfile.TemporaryDirectory(prefix="numstep-cube-") as temp_dir:
            os.chdir(temp_dir)
            builtins.input = lambda _prompt: str(size)

            namespace = runpy.run_path(
                str(CUBE_SOURCE),
                run_name="__main__",
            )

            generated_pdf = Path(namespace["OUTPUT_FILENAME"])
            if not generated_pdf.exists():
                raise RuntimeError(
                    "Original NumstepCube.py completed without creating its PDF."
                )

            return namespace["grid"], namespace["steps"], generated_pdf.read_bytes()
    finally:
        builtins.input = original_input
        os.chdir(original_cwd)


def export_json(grid, steps, puzzle_date, filename):
    """Serialize the exact grid generated by the original Cube program."""
    data = {
        "date": puzzle_date.isoformat(),
        "size": len(grid),
        "steps": steps,
        "solution": grid,
    }
    filename.parent.mkdir(parents=True, exist_ok=True)
    filename.write_text(json.dumps(data, indent=2), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(
        description="Generate the daily Numstep Cube using the original NumstepCube.py."
    )
    parser.add_argument("--date", default=None)
    parser.add_argument("--size", type=int, default=3)
    parser.add_argument("--output-root", default="games/numstep-cube")
    args = parser.parse_args()

    if args.size != 3:
        raise SystemExit("Numstep Cube currently supports only a 3cube.")

    puzzle_date = date.fromisoformat(args.date) if args.date else date.today()
    grid, steps, pdf_bytes = generate_from_original(puzzle_date, args.size)

    output_root = Path(args.output_root)
    json_path = output_root / "data" / f"{puzzle_date.isoformat()}.json"
    pdf_path = output_root / "printables" / f"{puzzle_date.isoformat()}.pdf"

    export_json(grid, steps, puzzle_date, json_path)
    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    pdf_path.write_bytes(pdf_bytes)

    print(f"Cube JSON created: {json_path}")
    print(f"Cube PDF created from NumstepCube.py: {pdf_path}")


if __name__ == "__main__":
    main()
