name: Generate Numstep

on:
  workflow_dispatch:

permissions:
  contents: write:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:

      - name: Get repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install reportlab

      - name: Generate Numstep
        run: |
          python numstep_daily_unique.py

      - name: Save generated puzzles
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add "*.json"

          git commit -m "Generate daily Numstep puzzle" || echo "No changes to commit"

          git push